### ISSUE TITLE
Missing class: order-invoice-total for PartPayment

### ISSUE THREAD

**Issue by AndreKlang** [PayEx/PayEx.Magento#11]
There is a reference to an order-invoice-total in PartPayment, but the file is missing.
Because of this, just having this module installed in a store breaks ALL orders (not just PartPayment-orders). That's because all totals is loaded and processed, for all orders.

https://github.com/PayEx/Magento-modules/blob/master/PartPayment/app/code/community/AAIT/PartPayment/etc/config.xml#L75

See error report in zip-file below. This specific order used Payex2 payment method.
[report.txt.zip](https://github.com/PayEx/Magento-modules/files/108019/report.txt.zip)

**Comment by AndreKlang** [comment]
This is actually related to https://github.com/PayEx/Magento-modules/issues/1
But for PartPayment instead..

**Comment by aait** [comment]
Implemented in 4421a3f8c03f5e0239c2b92d36de5aaa30b1ed29.
