### ISSUE TITLE
Tax & Payment Fee's

### ISSUE THREAD

**Issue by AndreKlang** [PayEx/PayEx.Magento#12]
Factoring & PartPayment have support for payment fee.
But none of them have support for tax.

See example lines:
https://github.com/PayEx/Magento-modules/blob/master/PartPayment/app/code/community/AAIT/PartPayment/Helper/Order.php#L378-L379

**Comment by aait** [comment]
https://github.com/PayEx/PayEx.Magento/commit/e713b769a54ec6fc2a5530b3b86803cdfd3d185c
