### ISSUE TITLE
AAIT phone-home-page is broken

### ISSUE THREAD

**Issue by AndreKlang** [PayEx/PayEx.Magento#14]
The module calls payex.aait.se to check the latest version available.
Along with the request is some private (and not anonymous) data.

The response looks like this:

```
Warning: var_export does not handle circular references in /var/www/clients/client18/web38/web/module/Application/src/Application/Controller/MetaController.php on line 227

... cut a few hundred lines ...

Warning: var_export does not handle circular references in /var/www/clients/client18/web38/web/module/Application/src/Application/Controller/MetaController.php on line 227

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 314953426 bytes) in /var/www/clients/client18/web38/web/module/Application/src/Application/Controller/MetaController.php on line 227
```

An example can be found [at this link](http://payex.aait.se/application/meta/check?key=V004t905i8O171l&site_url=http%3A%2F%2Fpaket.dev.int%2F&installed_version=3.0.0&mage_ver=1.9.1.0&edition=Community)

**Comment by aait** [comment]
PHP-exception at the statistics server as been fixed. The data sent is PayEx version and site-url. It is used by PayEx for statistical purposes to monitor who use the module.
