### ISSUE TITLE
Repeat payment from user account

### ISSUE THREAD

**Issue by Majklas** [PayEx/PayEx.Magento#18]
Can we have a link or method to repeat payment procedure for the client from his account?

**Comment by aait** [comment]
@Majklas are u talking about recurring payments? In case of a failed or not completed order, the products will remain in the basket and can be payed using the normal checkout.

**Comment by Majklas** [comment]
ok, I thought we could insert this link to email with custom order id (or hash). Now all I get is that client can only try to repeat payment within his account (he must be logged in of course) in recurring payments.. Is there any plans on generatin this custom link?

**Comment by aait** [comment]
@Majklas in which scenarios would this email with link be sent out? Usually if payment fails, there is no email sent out. Instead user will be redirected back to the checkout and have the possibility to retry payment. Depending on settings the pending order will be deleted eventually from Magento

**Comment by aait** [comment]
No feedback, closing issue meanwhile.
