### ISSUE TITLE
Error messages in frontend

### ISSUE THREAD

**Issue by AndreKlang** [PayEx/PayEx.Magento#2]
None (or few) of the error messages in checkout is customer friendly, examples:
- Using ssn 7302109074 (unapproved credit) at checkout gives message:
  - PayEx error: ValidationError_Generic (Purchase3rdParty)
- Using ssn 580604-5265 (old unapproved ssn):
  - in "fetch address" shows error:
    - ValidationError_Generic(Object reference not set to an instance of an object.)
  - in checkout shows error:
    - PayEx: PxOrder.GetAddressByPaymentMethod ValidationError_Generic (Object reference not set to an instance of an object.)
- failed Bankdebit
  - Order automatically canceled. Transaction is failed. The operation was cancelled by the client

If a customer sees any of these messages they are not going to have any idea what went wrong, and no chance of correcting the mistake

**Comment by aait** [comment]
Hi,
Once again thanks for your feedback.
The module just copies the answer it gets from PayeX API. That's all we know in most cases. 
I will relay your message to PayEx backend team, hoping they can diversify and improve error messages.

**Comment by asbjornu** [comment]
The modules can map the returned error code to more user friendly messages. The top 50 (in order of frequency) for redirect payments, are:
1. `OperationCancelledbyCustomer`
2. `PaymentRefusedByFinancialInstitution`
3. `IssuerCountryNotSupported`
4. `FraudPatternDetected`
5. `CardNotAcceptedForThisPurchase`
6. `CardStoreTypeNotSupported`
7. `CreditCheckNotApproved`
8. `Error_Generic`
9. `MaximumCountExceeded`
10. `CommunicationError`
11. `AcquirerComunicationError`
12. `UnexpectedCardIssuerAuthenticationRespons`
13. `Timeout`
14. `SignaturCheckFailed`
15. `MismatchOnName`
16. `MissingMerchantConfiguration`
17. `MaximumAmountExceeded`
18. `CardNotEligible`
19. `This transaction couldn't be completed`
20. `AmountNotEqualOrderLinesTotal`
21. `UsageCheck_MaximumAmountExceeded`
22. `FinancingFailed`
23. `IPX cannot perform the charging operation`
24. `CreditCheckRefNotValid`
25. `SSNVerificationFailed`
26. `ErrorReturnedByFinancialInstitution`
27. `Communications_Error_Seb`
28. `MerchantSettingsAuthenticationError`
29. `Internal_Error`
30. `InvalidData`
31. `ValidationError_InvalidParameter`
32. `AccountNumberNotFound`
33. `AuthenticationFailed`
34. `CardTypeNotFound`
35. `TechnicalError`
36. `BankIdClientError`
37. `3DSecureDirectoryServerError`
38. `InsufficientFunds`
39. `Communication_Error_Paypal`
40. `PanNotFound`
41. `NoMoneyOnAccount`
42. `ContractError_WrongAquirerBin`
43. `ClientAuthenticationTimeout`
44. `MobileAppDisabled`
45. `InvalidPostNumber`
46. `InvalidInput`
47. `SHB:FI_MissingBankAgreement`
48. `InvalidOrganizationNumber`
49. `External_Error_PayPal`
50. `NoRecordFound`

There exists 109 more exceptions that occur from time to time, but they are so rare that it's not of much value to spend time mapping them. For direct payment models like `FinancingInvoice`, we have the following error codes:
1.  `CreditCheckNotApproved`
2. `ValidationError_InvalidParameter`
3. `SSN_Country_Mismatch`
4. `Internal_Error`
5. `Error_Generic`

Not all of these need to be mapped, of course, but some are so explanatory that it should be possible to give a more user friendly error message.

**Comment by aait** [comment]
@asbjornu It's not a big deal to map the error code, but wouldn't it be better if the API itself sent clear error codes, preferably with an explanatory sentence?

**Comment by asbjornu** [comment]
@aait We'll improve this greatly with the next version of the API we have in works, but I doubt something significant is going to be done with the existing API.
