### ISSUE TITLE
Order rows is not sent to Payex

### ISSUE THREAD

**Issue by AndreKlang** [PayEx/PayEx.Magento#21]
When using one of "PayEx Financing Invoice" & "PayEx Financing Credit Account" the order rows is not sent to payex. At least they are not visible in Payex admin. This applies to both the authorization & capture transactions.

This however works for "PayEx Invoice Payments (Ledger Service)". My guess is that the method `getInvoiceExtraPrintBlocksXML` is not working properly.

See screenshot from Payex, there should be a link under "Additional Transaction Details", but that section is empty.

![skarmbild fran 2016-04-12 16 16 27](https://cloud.githubusercontent.com/assets/11595785/14463271/b0adf2c4-00ca-11e6-98b9-c0be9d27f281.png)

**Comment by pxsimon** [comment]
@AndreKlang: The orderlines aren't sent the same way for the different invoice-options and today you can't see the orderlines for PayEx Financing Invoice and PayEx Financing Credit Account in PayEx Admin, only on the actual invoice. This is not an issue in the module and should therefore be closed.

**Comment by AndreKlang** [comment]
@pxsimon Ok, fair enough. So how can I view "the actual invoice"? I can't find it in Payex admin, and there is no link to it in magento.

**Comment by pxsimon** [comment]
@AndreKlang in our test-environment it isn't possible to retrieve the invoice, in production however, there is two ways.
1. In PayEx Admin
![capture](https://cloud.githubusercontent.com/assets/16045704/14484461/f43c74da-0150-11e6-9377-796ccc8b035b.PNG)
2. You can retrieve the invoice with [InvoiceLinkGet](http://www.payexpim.com/technical-reference/pxorder/invoicelinkget/) - this is something we should look at implementing in the module.

**Comment by AndreKlang** [comment]
@pxsimon Ok, so what you're saying is that the testsystem is basically useless?

The order rows is not printed as they used to, and are only visible on the actual invoice, and that is only visible in production?

How are developers supposed to verify the data?

**Comment by PayExBent** [comment]
Hi,

Unfortunately, the lack of visible order lines in PayEx Merchant Admin is an open issue for Financing Invoice in test environment right now.

However, only order lines are sent to PayEx and these are validated the same way for test environment as in production. Since PayEx purchases the merchant transaction in Financing Invoice flow and PayEx will be the invoice issuer, we are making strict validation of order lines to make sure that the invoice we send out is correct. If the transaction does not get rejected, order lines have been supplied correctly.

Still, this is something we intend to improve in the future.

**Comment by AndreKlang** [comment]
@PayExBent 
Ok, you are working on improving the test environment? Nice, have an ETA on that?

I don't really buy the strict validating though, as can be seen above in the screen, it says VAT 0%. But the order-rows _do_ contain VAT. That seams to me as a clear reason for rejection?

Also, as I mentioned in #22, the tax for payment fee is shown incorrectly in Magento. So I suspect that it is also incorrect when it is sent to payex. But there is no way for me to verify that, since I can't see the results of the transactions.

**Comment by PayExBent** [comment]
I do not have an ETA for that unfortunately.

Regarding the issue with different VAT rates, VAT rates sent to PayEx are not validated towards what VAT rates are displayed in Magento interface. This is a different issue where different calculations for total price are made in the Magento interface.

VAT rates and prices that are actually sent to PayEx are however calculated correctly if the transaction is successful. Correctly in the sense that the total price, quantity and given VAT rates for all order lines add up to the Invoice amount and VAT amount given by merchant.
