### ISSUE TITLE
Payment fee: tax is not calculated properly

### ISSUE THREAD

**Issue by AndreKlang** [PayEx/PayEx.Magento#22]
The "tax" order-total does not include the tax from payment-fee.

I can not verify if it is sent to Payex correctly due to #21.
**Update:** I can now verify that it is sent correctly to payex for _PayEx Invoice Payments (Ledger Service)_. But still incorrect in Magento

See screens:

![skarmbild fran 2016-04-12 15 18 17](https://cloud.githubusercontent.com/assets/11595785/14463375/0d1bfaa6-00cb-11e6-886f-7ffdfeb82718.png)

![skarmbild fran 2016-04-12 15 20 56](https://cloud.githubusercontent.com/assets/11595785/14463398/16f721fe-00cb-11e6-8180-6428eca8959b.png)

![skarmbild fran 2016-04-12 15 19 30](https://cloud.githubusercontent.com/assets/11595785/14463407/211d3a24-00cb-11e6-9933-b4e15ee346fa.png)

**Comment by aait** [comment]
Fixed in v3.0.3
