### ISSUE TITLE
Clean up info that is presented to end user

### ISSUE THREAD

**Issue by AndreKlang** [PayEx/PayEx.Magento#23]
When viewing an order in customers account, often there is way more info about the payment than the customer needs, or understands for that matter.

See example below from "Payex Invoice", that could be cleaned up to be only "Payex Invoice, transaction number 9506753"

![skarmbild fran 2016-04-13 07 58 44](https://cloud.githubusercontent.com/assets/11595785/14484113/09134e68-014e-11e6-921d-8c6990eb0bc5.png)

**Comment by aait** [comment]
To display this info has been a request from some merchants, that's why we introduced it. So I dont know how to handle this request @asbjornu

**Comment by asbjornu** [comment]
@AndreKlang I don't quite understand the request here. From the screenshot you've posted, I can only see highly relevant, and in some cases; required information. But perhaps if it's possible to hide this information until the user requests it somehow, it would help? If the only option is to remove the information completely, I don't think we can fulfill this request. Ideas on how to improve this without permanently removing the information are welcome!

**Comment by AndreKlang** [comment]
@asbjornu: The only thing I see is relevant for the end user is the invoice #, or as it's called here "Transaction number".
In what scenario (as a end user) will I need to know that the status is "3"? Or that the method used was "PXFINANCINGINVOICE"?

And if I'd really need this in some kind of edge case, I'd start by contacting the stores customer service, and if they are unhelpful, I'd contact Payex customer service.

**Comment by asbjornu** [comment]
@AndreKlang Good points. I've had a chat with @PayEx/support about this and they agree we can reduce the entire "Betalningssätt" box to:

```
PayEx Faktura 2.0 Sverige
PayEx Transaction Number: 9506753
```

Probably translated to Swedish, if that's possible. The above works by inspecting the payment method string `PXFINANCINGINVOICESE` and figuring out that it is `PayEx Faktura 2.0` and `Sverige` from `SE`. Likewise `Norge` for `NO`. Other payment methods should be translated to similarly human readable strings that don't look cryptic and intimidating.

Sounds like a plan, @aait?

**Comment by aait** [comment]
First row is now Payment method title (defined in backend by admin).
Second row transaction number.
