### ISSUE TITLE
InvoiceLinkGet is not implemented

### ISSUE THREAD

**Issue by anderssonjakob** [PayEx/PayEx.Magento#24]
[InvoiceLinkGet](http://www.payexpim.com/technical-reference/pxorder/invoicelinkget/) should be implemented so the merchants can retrieve the invoice in the Magento-admin. It should be shown on an order if the invoice has been **Captured** and _Test mode_ is **OFF**.

**Comment by aait** [comment]
Hi Jakob, we especially proposed to implement InvoiceLinkGet, but at the time (March 2015) PayEx opted out for that feature in the module. Should I consider this as an official request for this feature? @asbjornu

**Comment by asbjornu** [comment]
@aait I assume this is a small job to implement, so go ahead. Create a new branch, pull-request it and reference this issue in it so we can close it up when the pull-request is merged. 👍
