### ISSUE TITLE
Payment fee: Can't refund

### ISSUE THREAD

**Issue by AndreKlang** [PayEx/PayEx.Magento#25]
Payment fee is not included when creating credit memo's, so it can't be refunded.

It should work the same as the shipping in the screen below, i.e. have it's own field pre filled.
![skarmbild fran 2016-04-13 08 32 41](https://cloud.githubusercontent.com/assets/11595785/14484794/15436cae-0153-11e6-9751-4f1cdd9758f7.png)

**Comment by aait** [comment]
Fixed in v3.0.3
