### ISSUE TITLE
Credit Card Autopay: Default feature for "Billing Agreements"

### ISSUE THREAD

**Issue by AndreKlang** [PayEx/PayEx.Magento#29]
I am a fan of using built-in features where ever possible. And since Magento has a built in feature for Billing Agreements, my question is, is there any reason to not use that here, instead of the custom table "payexautopay_agreement"?

From a quick review, "Billing Agreements" has the exact corresponding fields available as the custom table. The upside of using the built in feature is that the agreements can be viewed and revoked in admin, and the customer can also see it in their account when logged in.

This is just a suggestion, I have not used this feature myself before, but I guess is that it can help to further improve the usability of the module.
## Example how it looks in frontend:

![skarmbild fran 2016-04-13 11 35 37](https://cloud.githubusercontent.com/assets/11595785/14489167/0727f4be-016c-11e6-9c0f-c65a94cc0465.png)
## Example how it looks in admin:

![skarmbild fran 2016-04-13 11 36 17](https://cloud.githubusercontent.com/assets/11595785/14489170/0b1b451c-016c-11e6-8106-c616da28dbc4.png)

**Comment by aait** [comment]
@AndreKlang reason for this is that billing agreement didn't exist when the Autopay module was constructed. I agree with you that it is preferable to use the built in feature. It is up to PayEx to decide if and when we should implement the built in feature @asbjornu

**Comment by asbjornu** [comment]
@aait Sounds like the right thing to do, indeed.

**Comment by aait** [comment]
Fixed 9d5830b6e1c55eb055a32aa1e41cc52a6a00c28f
