### ISSUE TITLE
Issues in payment window for credit card

### ISSUE THREAD

**Issue by AndreKlang** [PayEx/PayEx.Magento#30]
I am aware that this is not related to the Magento module itself, but I can't find any "general" issue tracker. Feel free to move this to a more appropriate place.

When using _Payex Payment Window_ with _Credit Card_-view, there is two issues, both visible in the screens below.
1. There is no **Back** or _Cancel_-button. So if I change my mind and don't want to pay with credit card, I look for the back-button, can't find it, then hit the browsers back button. I then end up in magento, **With an empty cart** _(so it is somewhat magento-related after all)_
2. In desktop view there is an overview of the orders content (order rows) that can be opened or closed with the arrow on the right. However, in small view, the overview disappear, but the arrow is still there and still changes when clicked.

![skarmbild fran 2016-04-13 13 44 57](https://cloud.githubusercontent.com/assets/11595785/14492396/3e93b2ae-017f-11e6-8449-6467de1b7b7b.png)

![skarmbild fran 2016-04-13 13 45 23](https://cloud.githubusercontent.com/assets/11595785/14492400/4224a16c-017f-11e6-9e76-dbe391174e26.png)

**Comment by pxsimon** [comment]
@AndreKlang:
1. This is a setting in PayEx Admin.
It can be switched on under Merchant Configuration -> User Interface, as seen in the picture below.
![capture](https://cloud.githubusercontent.com/assets/16045704/14493468/ec378448-0185-11e6-9027-1461759b07e2.PNG) 
2. If you simulate this in the browser, you need to refresh the page for it to work when going from desktop-view to mobile-view.

These questions should in the future be sent directly to our support at e-mail: support.ecom@payex.com
