### ISSUE TITLE
Get Address: Country & Zip-fields

### ISSUE THREAD

**Issue by AndreKlang** [PayEx/PayEx.Magento#33]
It is not clear that the fields "Country" & "Postal code" is related to the get address feature.

**Scenario:** I am a new customer, that intends on using Credit Card as payment.

**What I see when going to checkout:**
![skarmbild fran 2016-04-13 15 00 33](https://cloud.githubusercontent.com/assets/11595785/14493935/77c468e4-0188-11e6-9f39-9148398d3ae2.png)

**My thoughts as a customer:**
- SSN is mandatory? What the f? I don't want to hand out my ssn to just anyone!
- Wait, I have to enter country, and zip-code twice? What? Why?
## Solution:

In a previous pull-request I had open, (before the module-merge), There was a feature that hid the country and zip-fields, **UNTIL** the customer started to fill out the ssn. And the red \* on SSN was removed.
That signals that fetching the address is optional, but if you want to fetch the address, you have to fill in postcode and country.
### Another improvement:

There should be a few different things to evaluate if the country-box really _HAVE_ to be shown.
Examples can be:
1. Does this store have more than one country enabled?
2. Can the ssn hint to which country it is? Norway and Sweden have different formats for instance.
3. Fallback: show the country field.

**Comment by aait** [comment]
@AndreKlang If u can refer me to that pull-request we can easily include that feature.

**Comment by AndreKlang** [comment]
@aait: Sorry, it actually wasn't part of the pull-request. It was in the other branch I had, commited with a bunch of other old fixes.

Any way, doesn't really matter since it isn't compatible now anyway. But you get the idea, hide what ever is not necessary until the user actually needs to fill it out.
