### ISSUE TITLE
Incorrect charging when cart is discounted using another VAT%

### ISSUE THREAD

**Issue by Surfbussen** [PayEx/PayEx.Magento#35]
Plugin disregards VAT settings on discount when calculating the correct amount to charge. 
This leads to wrong amount being billed.

This is not visible in magento BE or for customer in customer pages though = Owner of site needs to verify every discounted payment in PayEx admin pages to make sure payment is correct. Then correct it with the customer...

Example in attached files. Customer believes he/she should pay 1500 in this case. Screens:
- Discount is setup to count from price including VAT
- Discount rule is applied as it should. and works in Magento showing 1500 to pay/been paid.
- Payex charges 1050SEK

![discount setup](https://cloud.githubusercontent.com/assets/6685779/14949486/ae791ea4-104a-11e6-8e45-b06f1f9648d9.png)

![magento be](https://cloud.githubusercontent.com/assets/6685779/14949501/c4667018-104a-11e6-8448-5caa636932fe.png)

![payex payment](https://cloud.githubusercontent.com/assets/6685779/14949554/2e82f17e-104b-11e6-802f-d8647f68915a.png)

**Comment by Surfbussen** [comment]
Any progress on this? Charging the correct amount to customers must be seen as a core functionality?!

**Comment by aait** [comment]
We have added a classic mode for discount calculation. Please be sure to use it in your case. 
![classic](https://cloud.githubusercontent.com/assets/6286270/16522828/500664dc-3fa0-11e6-952f-b6ff51380ecf.png) https://github.com/PayEx/PayEx.Magento/commit/b681128dc15b2e3c4b465594ea3e3c76926ba66a
