### ISSUE TITLE
GetAddressByPaymentMethod error message

### ISSUE THREAD

**Issue by anderssonjakob** [PayEx/PayEx.Magento#39]
When a customer type in the wrong SSN or the SSN doesn't exist the error message that is shown looks like a technical failure.

![error message](https://cloud.githubusercontent.com/assets/16351407/15149453/e6454e0e-16c9-11e6-8500-551f25f3d15a.PNG)

That might discourage the customer from buying since he thinks it's wrong on the website, instead it should show a error message like, "SSN does not exist, please check that your SSN is correct".

**Comment by asbjornu** [comment]
Also, the error message should be output in the HTML and not as a JavaScript `alert()`.
