### ISSUE TITLE
VAT is "forgotten" when amount is transfered to Payex payment page

### ISSUE THREAD

**Issue by Surfbussen** [PayEx/PayEx.Magento#40]
I recently upgraded to the most recent build, all files. Previous version was only a few months old. It resulted in the payments being incorrectly sent to Payex, missing VAT. 

I reverted back to backup files and it works fine again.  Se below. 

Amount to charge is 1098. But when Payex gets the transaction it is 878,4 (transaction fails in the end)
![image](https://cloud.githubusercontent.com/assets/6685779/15583442/1d459bda-2376-11e6-88c0-96d355b0c26a.png)

Amount charged
![image](https://cloud.githubusercontent.com/assets/6685779/15584327/74270d86-237a-11e6-977a-30f21e1177ab.png)

**Comment by aait** [comment]
https://github.com/PayEx/PayEx.Magento/commit/b681128dc15b2e3c4b465594ea3e3c76926ba66a

**Comment by aait** [comment]
We have added a classic mode for discount calculation. Please be sure to use it in your case: 
![classic](https://cloud.githubusercontent.com/assets/6286270/16522797/261289c6-3fa0-11e6-9e0a-cb5d43fc4cb4.png)
