### ISSUE TITLE
Incorrect module version

### ISSUE THREAD

**Issue by p-makowski** [PayEx/PayEx.Magento#43]
Please increase module version accordingly to Semantic Versioning (http://semver.org/).
Otherwise composer projects defining dependency on "payex/payex" and using only "stable" tagged modules are not aware of changes done during few last days.

**Comment by siment** [comment]
This is a great suggestion

**Comment by aait** [comment]
2875d5476bb1c808df06903f5d0bb749bd9105c4

**Comment by asbjornu** [comment]
@p-makowski Did 2875d5476bb1c808df06903f5d0bb749bd9105c4 solve the problem? If not, can you please be more specific in what you mean?

**Comment by p-makowski** [comment]
@asbjornu Yes, that is perfect, thanks!

BTW: "_version_" node in _PayEx_Payments/app/etc/modules/PayEx_Payments.xml_ is not required as there is already one in _PayEx_Payments/app/code/community/PayEx/Payments/etc/config.xml_, You can remove it from _PayEx_Payments/app/etc/modules/PayEx_Payments.xml_ next time you do changes to this repository to avoid additional maintenance point.

**Comment by asbjornu** [comment]
@p-makowski: Excellent!

@aait ☝️ Comments?
