### ISSUE TITLE
PayEx Credit Card One-click Payments not visible

### ISSUE THREAD

**Issue by ghost** [PayEx/PayEx.Magento#44]
Hello,

PayEx Credit Card One-click Payments doesn't appear to shop, while all configuration fields are set in Magento. Also i have setup recurring profile to one of the products to test if it shows but no.

Does PayEx Credit Card onelick even support recurring profiles?

Creditcard oneclick works with normal products if not recurring profile set.

**Comment by aait** [comment]
Recurring profiles are not supported yet unfortunately.
