### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by asbjornu** [PayEx/PayEx.Magento#5]
We should have some automatic tests that can be executed to verify that the code is in working order. [Travis](https://travis-ci.org/) can execute [PHPUnit](https://phpunit.de/) tests, so we should look into adding some of those.

**Comment by asbjornu** [comment]
[MageCI](https://github.com/firegento/MageCI) might be worth looking into to solve this.

**Comment by aait** [comment]
Ready in v3.0.3
