### ISSUE TITLE
Outdated Finnish Bank names

### ISSUE THREAD

**Issue by pxjoachim** [PayEx/PayEx.Magento#55]
Magento version 1.14.3.0 (EE)
PX module version 3.1.3

The finnish bank names for direct debit payments are somewhat outdated. These are the correct names:

Aktia
Danske Bank (previously SAMPO)
Handelsbanken
Nordea
OP
POP Pankki
S-Pankki
Säästöpankki
Ålandsbanken

**Comment by olegisk** [comment]
Hi @pxjoachim Please provide bank codres for these labels.

**Comment by aait** [comment]
Hi @pxjoachim Please provide bank codres for these labels.

**Comment by pxjoachim** [comment]
Hello,

sure:

Aktia = AKTIA
Danske Bank = SAMPO
Handelsbanken Finland = SHB:FI
Nordea Finland = NB:FI
OP = OP
POP Pankki = POP
S-Pankki = SPANKKI
Säästöpankki = SP
Ålandsbanken = AALAND

**Comment by olegisk** [comment]
Fixed https://github.com/PayEx/PayEx.Magento/commit/a8c30aaa5e30fce0a72ed85acf5ebd501236e2ca
