### ISSUE TITLE
Not possible to install through Magento Marketplace

### ISSUE THREAD

**Issue by urbancrew** [PayEx/PayEx.Magento#61]
TCP connection reset by peer
![image](https://user-images.githubusercontent.com/11332687/31945946-e6e943ec-b8d0-11e7-85ee-62eeca13a3ba.png)

when trying to install from:
https://marketplace.magento.com/payex-payex-payments.html

good to know is that if you use community instead of magento market place access key then you won't receive message with "TCP connection reset by peer" if you disable https in downloader/lib/Mage/HTTP/Client/Curl.php on row 371

for example like this:
![image](https://user-images.githubusercontent.com/11332687/31946458-2e5e7bec-b8d2-11e7-96b3-a05d49dc9be3.png)

if you then try to proceed with installation then you'll get "access denied":
![image](https://user-images.githubusercontent.com/11332687/31946530-5c147c4e-b8d2-11e7-9ef2-65740b211abc.png)

**Comment by olegisk** [comment]
Magento Connect has been closed some times ango

**Comment by urbancrew** [comment]
ok, did not know, where does it say that it's closed? i can perfectly receive a magento market place access key for https://marketplace.magento.com/payex-payex-payments.html

screenshot:
![image](https://user-images.githubusercontent.com/11332687/31947168-fa75c87e-b8d3-11e7-8bcc-37ebf2d411f0.png)

**Comment by olegisk** [comment]
It's Magento Marketplace (not Connect)

**Comment by olegisk** [comment]
See https://magento.com/blog/magento-news/magento-connect-moving-marketplace

**Comment by urbancrew** [comment]
in the screenshot Magento Marketplace says: "Please copy the key and paste under the MCM for extension installation."
MCM is Magento Connect Manager

**Comment by olegisk** [comment]
Sorry, but it seem you are have problems with php configuration and SSL. It's server issue that should be solved by you.

**Comment by urbancrew** [comment]
Thanks I will check but the same issue appears on installation with or without SSL. and it's a straight forward installation of magento 1.9.3.6. Some extensions are possible to install and some are not.

**Comment by urbancrew** [comment]
This is a bug in magento, not related to payex extension.
