### ISSUE TITLE
form key

### ISSUE THREAD

**Issue by urbancrew** [PayEx/PayEx.Magento#64]
if magento option "Enable Form Key Validation On Checkout" is set to YES and PayEx option "Enable SSN Field for address filling" is set to YES then in checkout at Billing Address it is not possible to go further by clicking on the "Next" button. Nothing happens. If Form Key is disabled then it's working. Can you please check?

**Comment by urbancrew** [comment]
any progress on this issue?

**Comment by aait** [comment]
Itä's related to latest security updates for M1. We are working on a fix in coming days

**Comment by olegisk** [comment]
Fixed https://github.com/PayEx/PayEx.Magento/commit/fb2e0fb92411ec062e1793b7f30e920d581e4bfb
