### ISSUE TITLE
PayEx Financing Invoice Capture failure - character encoding åäö

### ISSUE THREAD

**Issue by patrickhrml** [PayEx/PayEx.Magento#68]
Capturing PayEx Financing Invoices fails due to orderlines product with ä (I assume it should be the same case for å and ö). 

The product is set with ä but in the financing orderlines it's coded to & auml ; and is the reason Capture is rejected, the orderlines is approved when manually changing the orderlines to ä instead of & auml ;

Tested with plugin version 3.1.9

**Comment by urbancrew** [comment]
status?

**Comment by olegisk** [comment]
Hello @patrickhrml @urbancrew ,
Please enable "Replace illegal characters" option to solve this problem
![configuration _ system _ magento admin](https://user-images.githubusercontent.com/871275/34549525-602d1266-f133-11e7-9d8b-51f16e869c03.png)

**Comment by urbancrew** [comment]
Hi, this option was already set to "yes".

**Comment by olegisk** [comment]
Please let me know full product name

**Comment by urbancrew** [comment]
@patrickhrml could you please check in payex admin which product names didn't pass through? I can't see in magento the specific products that failed capture. Besides åäö I can see other characters used in product names such as dashes "-", the sign for one half "½" and apostrof "'".

**Comment by patrickhrml** [comment]
@urbancrew Do you have a transaction number / orderRef for a failed attempt and I'll retrieve this information.

@olegisk An example for a customer is that the product is sent in Capture as: PanGourmet Original 85 - Avst&auml;llningshyllor Svart Sten 

Works with: PanGourmet Original 85 - Avställningshyllor Svart Sten

**Comment by urbancrew** [comment]
@patrickhrml , the only code I could find is ValidationError_InvalidParameter so I can't tell which transaction failed due to characters but for example here are some:
706744330
709130787
710668755

perhaps I missed some other code?

**Comment by patrickhrml** [comment]
@olegisk for @urbancrew example we have product name: PanGourmet Active 50 - Stekh&auml;ll

PanGourmet Active 50 - Stekhäll works
