### ISSUE TITLE
Rewrite the PDF documentation to Markdown

### ISSUE THREAD

**Issue by asbjornu** [PayEx/PayEx.Magento#7]
The documentation would be more accessible (through Google indexing) and for modification through the GitHub interface if it was written in [Markdown](https://help.github.com/articles/github-flavored-markdown/) instead of in a PDF file.

**Comment by aait** [comment]
https://github.com/PayEx/PayEx.Magento/commit/5dddfbb4ab82ea0f019d9c5327bbf4857731e820
