### ISSUE TITLE
12 percent tax calculation capturing PayEx Faktura error

### ISSUE THREAD

**Issue by patrickhrml** [PayEx/PayEx.Magento#73]
Hi!

When capturing a PayEx Faktura with a product containing 12 percent VatRate, the orderlines in Capture are calculated incorrectly. 

Product price (inc VAT): 89.00
withoutVAT: 79.46 (79.45 * 0,12 = 9.5352 = 9.54 when rounded to 2 decimals)
VatAmount: 9.54
VatPercent: 12

When Capture: PayEx: PxOrder.Capture5 ValidationError_InvalidParameter (Line number: 0 The 'VatRate' element is invalid - The value '12.01' is invalid according to its datatype 'VatRate' - The Enumeration constraint failed.)

Product Test01 with VatRate 12% in your magento7.aait testshop if test is needed.

**Comment by olegisk** [comment]
Hi @patrickhrml ,
Magento return follow values:
Price with tax = 89,
Price without tax = 79.46.

We are use this formula to calculate tax rate:
$x = (89 / 79.46 - 1) * 100;

PHP return float(12.006040775233)
But when formatting value PHP apply rounding: 12.01

May be use rounding with discarding the fractional part?

**Comment by patrickhrml** [comment]
Ok, so it's Magentos calculation that's being used? Is there a way to implement a different calculation to the plugin? This is how the calculation is made on PayEx end, that would return 12.00 (79.46 * 0.12 = 9.5352 = 9.54 + 79.46 = 89)

How to calculate UnitPrice and VatAmount in orderlines
To avoid getting errormessage “Errormessage : Description Order line amount differs from one calculated from unit price, vat rate and quantity. Product: Paper Captured/Credited total amount(X) differs from the calculated sum of order line amounts(X).” you need to calculate UnitPrice and VatAmount based on having max two decimals in NetAmount.
NetAmount 110.11
vatrate = 12
UnitPrice = NetAmount * Qty
UnitPrice = 110.11 * 1
UnitPrice = 110.11
UnitVatAmount = UnitPrice * VatRate / 100.0m (divide by 100 taking decimals into account)
UnitVatAmount = 110.11 * (12/100)
UnitVatAmount = 13.2132
VatAmount = UnitVatAmount * Qty
VatAmount = 13.2132 * 1
VatAmount = 13.2132
VatAmount = 13.21 (Rounded to two decimals)Based on UnitPrice = 110.11 and NetAmount 110.11 Payex will calculate Amount(inc vat) 123.83 (rounded two decimals).

----

Not sure if discarding the fractional part would maybe ruin the calculation in other cases for example 9.5352 wouldn't it stay at 9.53? Or maybe it would fix it as it's the VatRate which always will be X.00, is disabling the fractional part a setting in Magento?

**Comment by saumoor** [comment]
Status on this issue? 
Another merchant is experiencing the same issue but VAT is being calculated as 11.99 instead of 12.
