### ISSUE TITLE
Publish module as an extension on Magento Marketplace

### ISSUE THREAD

**Issue by asbjornu** [PayEx/PayEx.Magento#8]
As part of #6, when all tests pass and when the build is being run on the `master` branch, it should (if possible) be published an extension to the [Magento Marketplace](http://www.magentocommerce.com/magento-connect/), so it is up to date with the code living in `master` at all times.

**Comment by AndreKlang** [comment]
Actually, publishing every single push is not a good idea. However, publishing each release is the more common practice (similar to the way composer and all it's packages work).

A new release is created by adding a tag with the version number to git:

``` bash
git tag -a 1.2.3
git push --tags
```

Also, these will show up under "Releases" in github. (This repo currently has 0 releases)

**Comment by asbjornu** [comment]
@AndreKlang If there's only one branch, I agree. But as I've written in [PayEx Open Source Development Guidelines](/PayEx/Development.Guidelines/blob/master/open-source-development-guidelines.md), projects should follow [GitFlow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow/) or [GitHub Flow](https://guides.github.com/introduction/flow/), where the only commits occurring on the `master` branch are version-tagged merges (releases) from `develop`.

So the plan is to make this exactly as you describe; to publish every release. And every commit on master should be exactly that. :smiley:

**Comment by aait** [comment]
@asbjornu I think we can close this issue for Magento 1 at least?

**Comment by asbjornu** [comment]
@aait [The PayEx Payment Gateway extension is available on Magento Connect](https://www.magentocommerce.com/magento-connect/catalog/product/view/id/31962/), so: Yes. :smile:
